import { createFileRoute } from "@tanstack/react-router";
import { TopBar } from "@/components/app/TopBar";
import { Surface, SectionTitle } from "@/components/app/Surface";
import { StatusChip } from "@/components/app/StatusChip";
import { Download, FileSpreadsheet, FileText, CheckCircle2 } from "lucide-react";
import { useExportJobs, queryKeys } from "@/lib/hooks/api";
import { api } from "@/lib/api";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";

export const Route = createFileRoute("/_app/billing/exports")({ component: Page });

const TEMPLATES = [
  { name: "VAT Return (FTA)", desc: "Quarterly VAT 201 ready for FTA portal", format: "CSV", icon: FileSpreadsheet },
  { name: "Revenue Ledger", desc: "Per-invoice ledger w/ tax breakdown", format: "CSV", icon: FileSpreadsheet },
  { name: "Aged Receivables", desc: "0-30 / 31-60 / 61-90 / 90+ buckets", format: "PDF", icon: FileText },
  { name: "Subscription MRR", desc: "Plan-level MRR + churn cohort", format: "CSV", icon: FileSpreadsheet },
  { name: "Auto-bill summary", desc: "Per-cycle invoice generation log", format: "CSV", icon: FileSpreadsheet },
  { name: "Refund Register", desc: "All refunds w/ reason & approver", format: "PDF", icon: FileText },
];

function Page() {
  const queryClient = useQueryClient();
  const { data: recentJobs = [] } = useExportJobs();

  const handleGenerate = async (templateName: string, format: string, desc: string) => {
    try {
      await api.createExportJob({
        name: `${templateName} Export`,
        template: templateName,
        desc: desc,
        format: format,
      });
      await queryClient.invalidateQueries({ queryKey: queryKeys.exportJobs });
      toast.success("Export started", { description: `${templateName} has been created.` });
    } catch (e: any) {
      toast.error(e.message || "Failed to generate report");
    }
  };

  const handleDownload = async (id: string, fileName: string) => {
    try {
      await api.downloadExport(id, fileName);
      toast.success("Download started", { description: fileName });
    } catch (e: any) {
      toast.error(e.message || "Failed to download export file");
    }
  };

  return (
    <>
      <TopBar title="Export Reports" subtitle="Finance-grade exports · VAT, ledger, cohort, aged AR" />
      <div className="px-4 py-4 sm:px-6 sm:py-6 space-y-6">
        <Surface>
          <SectionTitle title="Export templates" sub="Generate FTA-compliant & internal finance reports" />
          <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
            {TEMPLATES.map(t => (
              <div key={t.name} className="group flex items-start gap-3 rounded-xl border border-border bg-surface-muted/40 p-4 hover:bg-surface-muted">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><t.icon className="h-4 w-4"/></div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2"><span className="text-[13px] font-black">{t.name}</span><span className="text-[10px] font-bold text-muted-foreground bg-surface px-1.5 py-0.5 rounded">{t.format}</span></div>
                  <div className="mt-0.5 text-[11.5px] text-muted-foreground">{t.desc}</div>
                  <button 
                    onClick={() => handleGenerate(t.name, t.format, t.desc)}
                    className="mt-2.5 inline-flex h-7 items-center gap-1 rounded-md bg-primary px-2 text-[11px] font-bold text-primary-foreground"
                  >
                    <Download className="h-3 w-3"/> Generate
                  </button>
                </div>
              </div>
            ))}
          </div>
        </Surface>
        <Surface padded={false}>
          <div className="px-5 py-4 border-b border-border"><SectionTitle title="Recent exports" sub="Last 30 days" /></div>
          <div className="overflow-x-auto">
            <table className="w-full text-[12.5px] min-w-[640px]">
              <thead className="bg-surface-muted text-[10.5px] font-bold uppercase tracking-wider text-muted-foreground">
                <tr><th className="px-4 py-3 text-left">File</th><th className="px-4 py-3 text-left">Generated by</th><th className="px-4 py-3 text-left">Size</th><th className="px-4 py-3 text-left">At</th><th className="px-4 py-3 text-right">Status</th><th className="px-4 py-3 text-right"></th></tr>
              </thead>
              <tbody>
                {recentJobs.map(r => (
                  <tr key={r.id} className="border-t border-border hover:bg-surface-muted/60">
                    <td className="px-4 py-3 font-bold">{r.fileName || r.name}</td>
                    <td className="px-4 py-3 text-muted-foreground">{r.by}</td>
                    <td className="px-4 py-3 tabular-nums">{r.size}</td>
                    <td className="px-4 py-3 text-muted-foreground">{r.at}</td>
                    <td className="px-4 py-3 text-right">
                      <StatusChip tone={r.status==="ready"||r.status==="completed"?"success":"neutral"}>
                        {(r.status==="ready"||r.status==="completed") && <CheckCircle2 className="h-2.5 w-2.5"/>}
                        {r.status}
                      </StatusChip>
                    </td>
                    <td className="px-4 py-3 text-right">
                      {(r.status==="ready"||r.status==="completed") && (
                        <button 
                          onClick={() => handleDownload(r.id, r.fileName || `${r.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.csv`)}
                          className="text-[11px] font-bold text-primary hover:underline"
                        >
                          Download
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Surface>
      </div>
    </>
  );
}

