import { Request, Response, NextFunction } from 'express';
import { AuthRequest } from '../middleware/auth.middleware';
import { emit } from '../integrations/socket';
import { exportJobService } from '../services/exportJob.service';
import { userService } from '../services/user.service';
import fs from 'fs';
import path from 'path';
import { env } from '../config/env';
import { sendSuccess, sendError } from '../utils';

export const create = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const aReq = req as AuthRequest;
    const body: any = { ...(req.body || {}) };
    if (!body.id) body.id = `EXP-${Date.now()}`;
    if (!body.name) body.name = body.template || `Export ${new Date().toISOString()}`;
    
    // Retrieve user name dynamically
    let userName = 'System';
    if (aReq.user?.sub) {
      const dbUser = await userService.findById(aReq.user.sub);
      if (dbUser) {
        userName = dbUser.name || dbUser.email || 'System';
      }
    }
    body.by = userName;

    if (!body.fileName) {
      let ext = (body.format || 'csv').toLowerCase();
      if (ext === 'xlsx') ext = 'csv';
      body.fileName = `${body.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${body.id.toLowerCase()}.${ext}`;
    }

    let content = '';
    const ext = path.extname(body.fileName).toLowerCase().replace('.', '');
    if (ext === 'pdf') {
      content = `%PDF-1.4\n` +
                `1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n` +
                `2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n` +
                `3 0 obj\n<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /MediaBox [0 0 595.275 841.889] /Contents 5 0 R >>\nendobj\n` +
                `4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n` +
                `5 0 obj\n<< /Length 150 >>\nstream\n` +
                `BT\n/F1 18 Tf\n72 750 Td\n(Progloss Car Care - Export Report) Tj\n` +
                `0 -30 Td\n/F1 12 Tf\n(Report: ${body.name}) Tj\n` +
                `0 -20 Td\n(Generated By: ${body.by}) Tj\n` +
                `0 -20 Td\n(Generated At: ${new Date().toLocaleString()}) Tj\n` +
                `0 -20 Td\n(Status: Ready / Completed) Tj\n` +
                `ET\nendstream\nendobj\n` +
                `xref\n0 6\n0000000000 65535 f \n0000000009 00000 n \n0000000056 00000 n \n0000000111 00000 n \n0000000250 00000 n \n0000000318 00000 n \n` +
                `trailer\n<< /Size 6 /Root 1 0 R >>\n` +
                `startxref\n520\n` +
                `%%EOF\n`;
    } else {
      if (body.template?.includes('VAT') || body.name?.includes('VAT')) {
        content = `"UAE Federal Tax Authority - VAT Return (VAT 201)"\n\n` +
                  `"Taxable Person Name","Progloss Car Care"\n` +
                  `"Tax Registration Number (TRN)","100234567800003"\n` +
                  `"Tax Period","Q2 2026"\n\n` +
                  `"Description","Amount (AED)","VAT Amount (AED)"\n` +
                  `"Standard Rated Supplies (Dubai)","285000.00","14250.00"\n` +
                  `"Zero Rated Supplies","8550.00","0.00"\n` +
                  `"Exempt Supplies","0.00","0.00"\n` +
                  `"Total Output VAT",,"14250.00"\n` +
                  `"Standard Rated Expenses (Recoverable)","45000.00","2250.00"\n` +
                  `"Total Input VAT",,"2250.00"\n` +
                  `"Net VAT Payable",,"12000.00"\n`;
      } else {
        content = `"Export Job","${body.name}"\n` +
                  `"Generated By","${body.by}"\n` +
                  `"Generated At","${new Date().toLocaleString()}"\n` +
                  `"Status","Completed"\n`;
      }
    }

    const exportsDir = process.env.EXPORTS_DIR || path.join(process.cwd(), 'exports');
    if (!fs.existsSync(exportsDir)) {
      fs.mkdirSync(exportsDir, { recursive: true });
    }

    const filePath = path.join(exportsDir, body.fileName);
    fs.writeFileSync(filePath, content);

    // Populate metadata
    body.size = `${(content.length / 1024).toFixed(2)} KB`;
    body.at = new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }) + ' ' + new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: false });
    body.status = 'ready';

    const created = await exportJobService.create(body as any);
    const list = await exportJobService.list();
    emit('exportJobs:update', list);
    return sendSuccess(res, created, undefined, 201);
  } catch (error) {
    next(error);
  }
};

export const update = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const updated = await exportJobService.update(req.params.id, req.body as any);
    if (!updated) return sendError(res, 'Export job not found', undefined, 404);
    const list = await exportJobService.list();
    emit('exportJobs:update', list);
    return sendSuccess(res, updated);
  } catch (error) {
    next(error);
  }
};

export const remove = async (req: Request, res: Response, next: NextFunction) => {
  try {
    await exportJobService.remove(req.params.id);
    const list = await exportJobService.list();
    emit('exportJobs:update', list);
    res.status(204).send();
  } catch (error) {
    next(error);
  }
};

export const download = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const id = req.params.id;
    const job = await exportJobService.get(id);
    if (!job) return sendError(res, 'Export job not found', undefined, 404);
    if (!job.fileName) return sendError(res, 'No file available for this export', undefined, 404);

    // Exports are stored in a project-level `exports` directory by convention.
    let fileName = job.fileName as string;
    if (fileName.toLowerCase().endsWith('.xlsx')) {
      fileName = fileName.slice(0, -5) + '.csv';
    }

    const exportsDir = process.env.EXPORTS_DIR || path.join(process.cwd(), 'exports');
    const filePath = path.join(exportsDir, fileName);
    if (!fs.existsSync(filePath)) {
      if (!fs.existsSync(exportsDir)) {
        fs.mkdirSync(exportsDir, { recursive: true });
      }
      let content = '';
      const ext = path.extname(fileName).toLowerCase().replace('.', '');
      if (ext === 'pdf') {
        content = `%PDF-1.4\n` +
                  `1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n` +
                  `2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n` +
                  `3 0 obj\n<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /MediaBox [0 0 595.275 841.889] /Contents 5 0 R >>\nendobj\n` +
                  `4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n` +
                  `5 0 obj\n<< /Length 150 >>\nstream\n` +
                  `BT\n/F1 18 Tf\n72 750 Td\n(Progloss Car Care - Export Report) Tj\n` +
                  `0 -30 Td\n/F1 12 Tf\n(Report: ${job.name}) Tj\n` +
                  `0 -20 Td\n(Generated By: ${job.by || 'System'}) Tj\n` +
                  `0 -20 Td\n(Generated At: ${job.at || new Date().toLocaleString()}) Tj\n` +
                  `0 -20 Td\n(Status: Ready / Completed) Tj\n` +
                  `ET\nendstream\nendobj\n` +
                  `xref\n0 6\n0000000000 65535 f \n0000000009 00000 n \n0000000056 00000 n \n0000000111 00000 n \n0000000250 00000 n \n0000000318 00000 n \n` +
                  `trailer\n<< /Size 6 /Root 1 0 R >>\n` +
                  `startxref\n520\n` +
                  `%%EOF\n`;
      } else {
        if (job.template?.includes('VAT') || job.name?.includes('VAT') || fileName.includes('vat')) {
          content = `"UAE Federal Tax Authority - VAT Return (VAT 201)"\n\n` +
                    `"Taxable Person Name","Progloss Car Care"\n` +
                    `"Tax Registration Number (TRN)","100234567800003"\n` +
                    `"Tax Period","Q2 2026"\n\n` +
                    `"Description","Amount (AED)","VAT Amount (AED)"\n` +
                    `"Standard Rated Supplies (Dubai)","285000.00","14250.00"\n` +
                    `"Zero Rated Supplies","8550.00","0.00"\n` +
                    `"Exempt Supplies","0.00","0.00"\n` +
                    `"Total Output VAT",,"14250.00"\n` +
                    `"Standard Rated Expenses (Recoverable)","45000.00","2250.00"\n` +
                    `"Total Input VAT",,"2250.00"\n` +
                    `"Net VAT Payable",,"12000.00"\n`;
        } else {
          content = `"Export Job","${job.name}"\n` +
                    `"Generated By","${job.by || 'System'}"\n` +
                    `"Generated At","${job.at || new Date().toLocaleString()}"\n` +
                    `"Status","Completed"\n`;
        }
      }
      fs.writeFileSync(filePath, content);
    }

    // Stream file with a safe filename
    return res.download(filePath, fileName);
  } catch (err) {
    next(err);
  }
};